### ISSUE TITLE
A command to display the generated JS code

### ISSUE THREAD

**Issue by sjrd** [scalafiddle/scalafiddle-editor#27]
Scala.jsFiddle had a command (hidden behind Ctrl+J) to show the generated .js code for the snippet. Could we have something similar in Scala Fiddle?

**Comment by sjrd** [comment]
Could Ctrl/Cmd+J also clear the right pane first? Try using it on https://scalafiddle.io/sf/jsgjSoT/1 and you'll immediately see that it's unreadable if the right pane still contains the rendering.

**Comment by ochrons** [comment]
Ah right, it only clears the text div, not the canvas.
