### ISSUE TITLE
fix in Chrome

### ISSUE THREAD

**Issue by antonkulaga** [scalafiddle/scalafiddle-editor#3]
I cannot type anything in the editor when I use chrome (it works ok in Firefox) 
![screenshot from 2016-09-13 13 42 49](https://cloud.githubusercontent.com/assets/842436/18470990/083e3966-79b8-11e6-884e-80a3de96bc76.png)

**Comment by ochrons** [comment]
Please check if the latest update (that fixed a similar issue in Safari) also fixed this.

**Comment by antonkulaga** [comment]
Now the code is visible but I do not see the Result =(

**Comment by ochrons** [comment]
Ok, probably the same issue as with editor DIV, gotta change the CSS for the result side as well. Too bad cannot test it locally :)

Can you try manually changing CSS in Chrome, go to the #output DIV and add `position: absolute` to its element.style and see what happens?

**Comment by ochrons** [comment]
Fixed in the latest update with some CSS changes.
