### ISSUE TITLE
println(null) does not work like Predef.println

### ISSUE THREAD

**Issue by sjrd** [scalafiddle/scalafiddle-editor#31]
`println(null)` causes this to be displayed in the right pane:

> ERROR: instance is null

(in red), and then the execution stops.

I expect that the following be displayed instead:

> null

as if I had called `println("null")`

That the behavior is different from `Predef.println` is annoying when one tries to explain some bad behavior of a snippet, as we cannot demonstrate the real issue.

**Comment by ochrons** [comment]
Fixed now.
