### ISSUE TITLE
Worksheet Mode

### ISSUE THREAD

**Issue by adamvoss** [scalafiddle/scalafiddle-editor#42]
The Scala Worksheet seems to be popular in both Eclipse and IntelliJ.  Users may find it useful if ScalaFiddle supported this mode as well.

For example, this would allow learners to follow along with videos for [_Functional Programming Principles in Scala_ coursera course](https://www.coursera.org/learn/progfun1/) using just a web browser.

**Comment by ochrons** [comment]
You can use the new Scala Center Scastie for a more worksheet like experience. Give it a try!
