### ISSUE TITLE
My old scala-js-fiddle gist links result in 404

### ISSUE THREAD

**Issue by gabrieljones** [scalafiddle/scalafiddle-editor#43]
http://www.scala-js-fiddle.com/gist/11b36945bd5393042c11
http://www.scala-js-fiddle.com/gist/5dd062ed369a354a3c33
http://www.scala-js-fiddle.com/gist/68ccf07a8cdb5f537d9f

**Comment by ochrons** [comment]
Yeah, gists are not supported and the new ScalaFiddle is not directly compatible with the old one. You'll need to port your fiddles to the new system.
