### ISSUE TITLE
ScalaFiddle.scala:-5: ERROR: Library com.thoughtworks.binding %%% binding % 10.0.1 is not allowed

### ISSUE THREAD

**Issue by Atry** [scalafiddle/scalafiddle-editor#47]
I choose Binding.scala 10.0.1 in "All versions", and I got an error
```
ScalaFiddle.scala:-5: ERROR: Library com.thoughtworks.binding %%% binding % 10.0.1 is not allowed
```

See https://scalafiddle.io/sf/dGkVqlV/9

**Comment by ochrons** [comment]
Yea, for some reason the compiler backend is not updating the libraries automatically from the editor like it should. It requires a manual restart of the compiler services. Now it works OK again.

**Comment by Atry** [comment]
@ochrons Errors for 10.0.2 now.
`ScalaFiddle.scala:-5: ERROR: Library com.thoughtworks.binding %%% binding % 10.0.2 is not allowed`

**Comment by ochrons** [comment]
Restarted the services again, should work now :)
