### ISSUE TITLE
Implement responsive design

### ISSUE THREAD

**Issue by megri** [scalafiddle/scalafiddle-editor#64]
The site is not usable with mobile style devices. This could be fixed either by applying CSS media queries for appropriate sizes, or making the whole design fluid.

Applying a CSS-framework such as bootstrap (it's honestly been a while since I did UI styling so I don't know what's hip these days) would go a long way.

**Comment by ochrons** [comment]
Thanks! This sort of duplicates #49 so let's move the discussion there.
