### ISSUE TITLE
Foldable.traverse_ from cats on ScalaFiddle returns "undefined"

### ISSUE THREAD

**Issue by Fabs** [scalafiddle/scalafiddle-editor#70]
This is the fiddle:
https://scalafiddle.io/sf/CjQOb84/0

Code:
```scala
import cats.implicits._
import cats.Foldable

def parseInt(s: String): Option[Int] = {
  val x = Either.catchOnly[NumberFormatException](s.toInt).toOption
  x foreach println
  x
}

println(Foldable[List].traverse_(List("1", "2"))(parseInt).get)
```

Result:
```Output
1
2
undefined
````
Expected:
```Output
1
2
Some(3)
````

I am new to this Scala world, so please let me know if you recommend me posting the bug at Cats or at Scala.js

**Comment by ochrons** [comment]
Probably best to discuss on the typelevel/cats gitter channel first. Definitely nothing that ScalaFiddle can do about this :)

**Comment by Fabs** [comment]
Alright, thanks.

Actually, for further readers coming here. I just noticed that the problem might be in the Scala Exercises I was trying to do, the signature of `Foldable[A].traverse_` returns `G[Unit]`. So it makes sense to be `undefined` in Scala.js. So expecting `Some(3)` is actually wrong, it should be `Some(())`.
