### ISSUE TITLE
Support for JS/CSS dependencies

### ISSUE THREAD

**Issue by ochrons** [scalafiddle/scalafiddle-editor#8]
Allow specifying separate JS/CSS library dependencies (like React, Bootstrap etc) and also allow providing JS deps in for Scala libs.

**Comment by aappddeevv** [comment]
How is the output from the compile loaded into the browser? Assuming you load the scala part into an iframe for execution and with it, some type of html also generated, we could create a webpack bundle that resolves all require's to CDNs. But you would need to have the server run node.js for running webpack.

**Comment by mkotsbak** [comment]
Seems this can be closed now.

**Comment by ochrons** [comment]
Yea, it's been completed ages ago :)
